######################################################################
# Automatically generated by qmake (3.0) ? 11? 2 11:55:04 2015
######################################################################

TEMPLATE = app
TARGET = qmlcoop
INCLUDEPATH += .

QT += quick

# Input
HEADERS += message.h
SOURCES += message.cpp main.cpp

RESOURCES += qmlcoop.qrc
