######################################################################
# Automatically generated by qmake (3.0) ? 11? 2 11:55:04 2015
######################################################################

TEMPLATE = app
TARGET = qmlcoop
INCLUDEPATH += . /usr/local/include

QT += quick qml

# Input
HEADERS += plug.h
SOURCES += main.cpp

RESOURCES += qmlcoop.qrc
